// Hash all inline scripts generated by Next's static export. Do not enable unsafe-inline for scripts.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
const [root, target] = process.argv.slice(2);
if (!root || !target) throw new Error('Usage: node build-csp.mjs <export-dir> <output-file>');
const hashes = new Set();
function walk(dir) {
  for (const file of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, file.name);
    if (file.isDirectory()) walk(path);
    else if (path.endsWith('.html')) {
      const html = readFileSync(path, 'utf8');
      for (const match of html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)) {
        if (!/\bsrc\s*=/i.test(match[1]) && match[2]) {
          hashes.add(`'sha256-${createHash('sha256').update(match[2]).digest('base64')}'`);
        }
      }
    }
  }
}
walk(root);
const policy = `default-src 'none'; script-src 'self' ${[...hashes].join(' ')}; style-src 'self'; img-src 'self' data:; font-src 'self'; connect-src 'self'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'; object-src 'none'`;
writeFileSync(target, `header Content-Security-Policy "${policy}"\n`);
console.log(`Generated CSP with ${hashes.size} inline-script hashes.`);
